# Use this file to set options for the app

default:
 anon_locations: false
 display_signup_trend: false
 
 # Options for loading trips and locations
 load_trips_start_ndays: 7
 max_documents_for_mod_load_trips: 10000 # 500 for testing with test-data
 # Limiting to 300 megabytes worth of trips and locations:
 # each trip doc is ~1500 characters * 2 bytes/character (UTF8) 
 # 		300 *10^6 bytes/(3*10^3 bytes/document) = 100,000 documents 
 
 min_locations_per_trip: 30 # 4 for easier testing with test-data
 
 cols_to_remove_from_participts_table:
  - first_trip_datetime
  - last_trip_datetime
  # More to remove for this deployment:
  - n_active_days
  - first_trip_local_datetime
  - first_get_call
  - first_put_call
  - first_diary_call
  
 cols_to_remove_from_trips_table:
  - start_fmt_time0 
  - start_local_dt_timezone
  - start_fmt_time
  - end_fmt_time0
  - end_local_dt_timezone
  - end_fmt_time
  - end_loc_coordinates
  - start_loc_coordinates
  - duration
  - distance
  - geometry
  - source
  - cleaned_trip

 cols_to_remove_from_map_popup:
  - start_fmt_time0
  - start_local_dt_timezone
  - start_fmt_time
  - end_fmt_time0
  - end_local_dt_timezone
  - end_fmt_time
  - end_loc_coordinates
  - start_loc_coordinates
  - duration
  - distance
  - location_points
  - source
  - cleaned_trip
  
  
 # Set the labels to display for the participant data 
 col_labels_for_participts:
   user_id:             user id
   update_ts:           last profile update  
   client:              UI channel 
   client_app_version:  smartphone app version
   client_os_version:   android/iOS version
   curr_platform:       android/iOS 
   phone_lang:          language
   n_trips:             Total trips
   n_trips_today:       Trips today
   n_active_days:       Number of days with at least one trip
   first_trip_local_datetime: First trip date
   last_trip_local_datetime: Last trip date
   n_days:         Number of days since app install   
   unconfirmed:    unlabeled
   first_get_call: first app communication
   last_get_call:  last app communication
   first_put_call: first data upload
   last_put_call:  last data upload
   first_diary_call: first app launch
   last_diary_call:  last app launch
  




