# c("user_id", "update_ts", "client", "curr_platform", "n_trips",
# "n_trips_today", "n_active_days", "first_trip_datetime", "last_trip_datetime",
# "first_trip_local_datetime", "last_trip_local_datetime", "n_days",
# "first_get_call", "last_get_call", "first_put_call", "last_put_call",
# "first_diary_call", "last_diary_call")

default:
 display_signup_trend: false
 cols_to_remove_from_participts_table:
  - first_trip_datetime
  - last_trip_datetime
  # More to remove for this deployment: first_XXX
  - first_trip_local_datetime
  - first_get_call
  - first_put_call
  - first_diary_call



